version: "3"
services:

  frontend:
    container_name: client
    build:
      dockerfile: dockerfile
      context: ./frontend
    
    volumes:
      - ./:/app

  backend:
    container_name: server
    build:
      dockerfile: dockerfile
      context: ./backend

  nginx:
    image: nginx
    depends_on:
      - frontend
      - backend
    volumes: 
      - ./nginx/local.conf:/etc/nginx/conf.d/default.conf

    ports:
      - 8000:80


    

