version: "3"
services:
  frontend:
    container_name: client
    build:
      dockerfile: dockerfile
      context: ./frontend

  backend:
    container_name: server
    build:
      dockerfile: dockerfile
      context: ./backend

  nginx:
    depends_on:
      - frontend
      - backend

    build:
      dockerfile: dockerfile
      context: ./nginx

    ports:
      - 8000:80


    

